Kanban/Kanban/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/v1/", include("core.urls")),
    path("api/v1/dj-rest-auth/", include("dj_rest_auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/v1/dj-rest-auth/registration/",
         include("dj_rest_auth.registration.urls")),
]

Kanban/core/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from .views import (UserViewSet, RoleViewSet, DeveloperProfileViewSet, BoardViewSet,
                    ListViewSet, CardViewSet, CommentViewSet)

router = SimpleRouter()
router.register("users", UserViewSet, basename="users")
router.register("roles", RoleViewSet, basename="roles")
router.register("developerprofile", DeveloperProfileViewSet, basename="developerprofile")
router.register("board", BoardViewSet, basename="board")
router.register("list", ListViewSet, basename="list")
router.register("card", CardViewSet, basename="card")
router.register("comment", CommentViewSet, basename="comment")
urlpatterns = router.urls

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import (
    login, home, view_task, user_projects, get_task, project_tasks, view_issue,
    all_tasks, all_issues, create_project, create_issue, create_task, complete_profile,
    add_developer
    )
urlpatterns = [
    # path("login/", Login.as_view(), name="login"),
    path("login/", login, name="login"),
    path("", home, name="home"),
    path('view_task/<int:task_id>/', view_task, name='view_task'),
    path('view_issue/<int:issue_id>', view_issue, name='view_issue'),
    path('projects/', user_projects, name='user_projects'),
    path('tasks/<str:status_name>/<int:status_id>', get_task, name='get_task'),
    path('project/<int:project_id>/tasks', project_tasks, name='project_tasks'),
    path('tasks/', all_tasks, name="all_tasks"),
    path('issues/', all_issues, name="all_issues"),
    path('create-project/', create_project, name='create_project'),
    path('add_developer/', add_developer, name='add_developer'),
    path('create-task/', create_task, name='create_task'),
    path('create-issue/', create_issue, name='create_issue'),
    path('complete-profile/', complete_profile, name='complete_profile'),
]

kanban_project/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include('core.urls')),
    # path("", Home.as_view(), name="home"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class UserTechnology(models.Model):
    user_technology_id = models.AutoField(primary_key=True)
    technology_name = models.CharField(max_length=255)
    def __str__(self):
        return self.technology_name

class UserRole(models.Model):
    user_role_id = models.AutoField(primary_key=True)
    role_name = models.CharField(max_length=255)
    def __str__(self):
        return self.role_name

class UserDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_role = models.ForeignKey(UserRole, on_delete=models.CASCADE)
    user_technology = models.ForeignKey(UserTechnology, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
class Project(models.Model):
    project_id = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=255)
    project_description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.project_name


class UserProject(models.Model):
    user_project_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)


class UserTask(models.Model):
    user_task_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey('Task', on_delete=models.CASCADE)


class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=255)
    task_description = models.TextField()
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.ForeignKey('TaskStatus', on_delete=models.CASCADE)
    task_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_tasks')

    def __str__(self):
        return self.task_name


class Issue(models.Model):
    issue_id = models.AutoField(primary_key=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    issue_name = models.CharField(max_length=255)
    task_description = models.TextField()
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.ForeignKey('IssueStatus', on_delete=models.CASCADE)
    issue_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_issues')
    
    def __str__(self):
        return self.issue_name


class IssueStatus(models.Model):
    status_id = models.AutoField(primary_key=True)
    status_name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.status_name


class TaskStatus(models.Model):
    status_id = models.AutoField(primary_key=True)
    status_name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.status_name

core/forms.py
# In your app's forms.py file
from django import forms
from .models import UserDetail, UserProject

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserDetail
        fields = ['user_role', 'user_technology']
        widgets = {
            'user_role': forms.Select(attrs={'class': 'form-control'}),
            'user_technology': forms.Select(attrs={'class': 'form-control'}),
        }


class UserProjectForm(forms.ModelForm):
    class Meta:
        model = UserProject
        fields = ['user', 'project']
        widgets = {
            'user': forms.Select(attrs={'class': 'form-control'}),
            'project': forms.Select(attrs={'class': 'form-control'}),
        }

Kanban/core/views.py
from django.contrib.auth import get_user_model
from .models import Role, Technology, DeveloperProfile, Board, List, Card, Comment
# from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser
from .serializers import UserSerializer, RoleSerializer, TechnologySerializer, DeveloperProfileSerializer, BoardSerializer, ListSerializer, CardSerializer, CommentSerializer


# Create your views here.
class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAdminUser, )
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


class RoleViewSet(viewsets.ModelViewSet):
    queryset = Role.objects.all()
    serializer_class = RoleSerializer


class TechnologyViewSet(viewsets.ModelViewSet):
    queryset = Technology.objects.all()
    serializer_class = TechnologySerializer


class DeveloperProfileViewSet(viewsets.ModelViewSet):
    queryset = DeveloperProfile.objects.all()
    serializer_class = DeveloperProfileSerializer


class BoardViewSet(viewsets.ModelViewSet):
    queryset = Board.objects.all()
    serializer_class = BoardSerializer


class ListViewSet(viewsets.ModelViewSet):
    queryset = List.objects.all()
    serializer_class = ListSerializer


class CardViewSet(viewsets.ModelViewSet):
    queryset = Card.objects.all()
    serializer_class = CardSerializer


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

core/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.http import HttpResponse
from core.models import Task
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from .models import Task, TaskStatus, UserProject, Issue, Project, IssueStatus, UserDetail
from django.contrib.auth.models import User
from .forms import UserProfileForm, UserProjectForm
from django.views.generic import TemplateView
from django.contrib import messages

class Home(TemplateView):
    template_name = "core/logintest.html"

@login_required(login_url="/login/")
def view_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task = Task.objects.get(pk=task_id)
    project = task.project
    users = User.objects.filter(userproject__project=project)
    status = TaskStatus.objects.all()
    if request.method == 'POST':
        task.task_name = request.POST.get('task_name')
        task.task_description = request.POST.get('task_description')
        task.assigned_to = User.objects.get(id=int(request.POST.get('assigned_to')))
        task.status = TaskStatus.objects.get(status_id=int(request.POST.get('status')))
        task.save()
        return redirect('/')

    return render(request, 'core/task_detail.html', {'task': task, 'users': users, 'task_statuses': status})

@login_required(login_url="/login/")
def view_issue(request, issue_id):
    issue = Issue.objects.get(pk=issue_id)
    project = issue.project
    users = User.objects.filter(userproject__project=project)
    status = TaskStatus.objects.all()
    if request.method == 'POST':
        issue.task_name = request.POST.get('task_name')
        issue.task_description = request.POST.get('task_description')
        issue.assigned_to = User.objects.get(id=int(request.POST.get('assigned_to')))
        issue.status = IssueStatus.objects.get(status_id=int(request.POST.get('status')))
        issue.save()
        return redirect('/')

    return render(request, 'core/task_detail.html', {'task': issue, 'users': users, 'task_statuses': status})


def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect("/")

        else:
            return render(request, 'core/login.html', {'error_message': 'Invalid credentials'})

    return render(request, template_name="core/login.html")


def complete_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            messages.success(request, 'Profile completed successfully.')
            return redirect('/')  # Redirect to the home page or another appropriate view
    else:
        form = UserProfileForm()

    return render(request, 'core/complete_profile.html', {'form': form})

@login_required(login_url="/login/")
def home(request):
    recent_projects = Project.objects.filter(userproject__user=request.user).order_by('-created_at')[:3]
    task_counts = (
        Task.objects
        .filter(assigned_to=request.user)
        .values('status__status_name', 'status__status_id')
        .annotate(count=Count('status'))
    )
    tasks = (
        Task.objects
        .filter(assigned_to=request.user)
        .values('task_name', 'project__project_name', 'task_id')
    )

    issues = (
        Issue.objects
        .filter(assigned_to=request.user)
        .values('issue_name', 'project__project_name', 'issue_id')
    )
    user_details = UserDetail.objects.filter(user=request.user)
    if not user_details:
        return redirect("/complete-profile/")
    context = {
        'task_counts': task_counts,
        'tasks': tasks,
        'issues': issues,
        'recent_projects': recent_projects,
        'user_details': user_details,
    }
    # breakpoint()

    return render(request, template_name="core/home.html", context=context)

def user_projects(request):
    user = request.user
    user_projects = UserProject.objects.filter(user=user).select_related('project')
    projects = []

    for user_project in user_projects:
        project = user_project.project
        project.task_count = Task.objects.filter(project=project).count()
        project.issue_count = Issue.objects.filter(project=project).count()
        projects.append(project)

    return render(request, 'core/user_projects.html', {'projects': projects})

def get_task(request, status_name, status_id):
    tasks = Task.objects.filter(status_id=status_id).select_related('project')
    context = {'tasks': tasks}
    return render(request, 'core/get_tasks.html', context)


@login_required(login_url="/login/")
def project_tasks(request, project_id):
    # Get the project
    project = Project.objects.get(pk=project_id)

    # Get all task statuses
    task_statuses = TaskStatus.objects.all()

    # Fetch tasks for each status for the given project
    tasks_by_status = {}
    for status in task_statuses:
        tasks_by_status[status.status_name] = Task.objects.filter(
            project=project,
            status=status
        ).values('task_name', 'task_description', 'assigned_to__username')

    context = {
        'project': project,
        'tasks_by_status': tasks_by_status,
    }

    return render(request, template_name="core/project_tasks.html", context=context)


def all_tasks(request):
    tasks = (
        Task.objects
        .filter(assigned_to=request.user)
        .values('task_name', 'project__project_name', 'task_id')
    )
    context = {

        "tasks":tasks
        }
    return render(request, template_name="core/tasks.html", context=context)

def all_issues(request):
    issues = ( # need to change query
        Issue.objects
        .filter(assigned_to=request.user)
        .values('issue_name', 'project__project_name', 'issue_id')
    )
    context = {
        "issues":issues
    }
    return render(request, template_name="core/issues.html", context=context)

def create_project(request):
    if request.method=="POST":
        return HttpResponse("Submitted form")
    return render(request, template_name="core/create_project.html")


def create_issue(request):
    if request.method=="POST":
        return HttpResponse("Submitted form")
    return render(request, template_name="core/create_issue.html")


def create_task(request):
    if request.method == "POST":
        project = Project.objects.get(project_id=int(request.POST.get('project')))
        task_name = request.POST.get('task_name')
        task_description = request.POST.get('task_description')
        assigned_to = request.POST.get('assigned_to')
        assigned_user = User.objects.get(id=int(assigned_to))
        status = TaskStatus.objects.get(status_id=1)
        task_owner = request.user

        task = Task.objects.create(
            project=project,
            task_name=task_name,
            task_description=task_description,
            assigned_to=assigned_user,
            status=status,
            task_owner=task_owner
        )
        task.save()
        return redirect('/')
    projects = Project.objects.filter(userproject__user=request.user)
    users = User.objects.all()

    context = {
        'projects': projects,
        'users': users,
    }

    return render(request, template_name="core/create_task.html", context=context)

def create_issue(request):
    if request.method == "POST":
        project = Project.objects.get(project_id=int(request.POST.get('project')))
        issue_name = request.POST.get('issue_name')
        issue_description = request.POST.get('issue_description')
        assigned_to = request.POST.get('assigned_to')
        assigned_user = User.objects.get(id=int(assigned_to))
        status = IssueStatus.objects.get(status_id=1)
        issue_owner = request.user

        issue = Issue.objects.create(
            project=project,
            issue_name=issue_name,
            task_description=issue_description,
            assigned_to=assigned_user,
            status=status,
            issue_owner=issue_owner
        )
        issue.save()
        return redirect('/')
    
    projects = Project.objects.all()
    users = User.objects.all()

    context = {
        'projects': projects,
        'users': users,
    }

    return render(request, template_name="core/create_issue.html", context=context)


def add_developer(request):
    if request.method == 'POST':
        form = UserProjectForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Developer added to the project successfully.')
            return redirect('/')
    else:
        form = UserProjectForm()

    return render(request, 'core/userproject.html', {'form': form})

templates/core/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- Add your CSS and other head elements here -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Social Login</title>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/core/complete_profile.html
{% extends 'core/_base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Complete Your Profile</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save Profile</button>
    </form>
</div>
{% endblock %}

templates/core/create_issue.html
{% extends 'core/_base.html' %}

{% block content %}
    <div class="container">
        <h2>Create Issue</h2>
        <form method="post" action="{% url 'create_issue' %}" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
                <label for="project" class="form-label">Project:</label>
                <select name="project" class="form-control" required>
                    <option value="" selected disabled>Select a project</option>
                    {% for project in projects %}
                        <option value="{{ project.project_id }}">{{ project.project_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="issue_name" class="form-label">Issue Name:</label>
                <input type="text" name="issue_name" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="issue_description" class="form-label">Issue Description:</label>
                <textarea name="issue_description" class="form-control" required></textarea>
            </div>

            <div class="mb-3">
                <label for="assigned_to" class="form-label">Assigned To:</label>
                <select name="assigned_to" class="form-control" required>
                    <option value="" selected disabled>Select an option</option>
                    {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Create Issue</button>
        </form>
    </div>
{% endblock %}

templates/core/create_task.html
{% extends 'core/_base.html' %}

{% block content %}
<div class="container">
        {% if projects.exists %}
        <h2>Create Task</h2>
        <form method="post" action="{% url 'create_task' %}" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
                <label for="project" class="form-label">Project:</label>
                <select name="project" class="form-control" required>
                    <option value="" selected disabled>Select a project</option>
                    {% for project in projects %}
                        <option value="{{ project.project_id }}">{{ project.project_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="task_name" class="form-label">Task Name:</label>
                <input type="text" name="task_name" class="form-control" required>
            </div>

            <div class="mb-3">
                <label for="task_description" class="form-label">Task Description:</label>
                <textarea name="task_description" class="form-control" required></textarea>
            </div>

            <div class="mb-3">
                <label for="assigned_to" class="form-label">Assigned To:</label>
                <select name="assigned_to" class="form-control" required>
                    <option value="" selected disabled>Select an option</option>
                    {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Create Task</button>
        </form>
    {% else %}
        <h2>You are not a part of any project</h2>
        <p>You cannot create a task as you are not associated with any project.</p>
    {% endif %}
    </div>
{% endblock %}

templates/core/get_tasks.html
<!-- tasks_table.html -->
{% extends 'core/_base.html' %}

{% block content %}
  <h2>All Tasks</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Task ID</th>
        <th>Task Name</th>
        <th>Task Description</th>
        <th>Assigned To</th>
        <th>Project Name</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Status</th>
        <th>Task Owner</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        <tr>
          <td>{{ task.task_id }}</td>
          <td>{{ task.task_name }}</td>
          <td>{{ task.task_description }}</td>
          <td>{{ task.assigned_to.username }}</td>
          <td>{{ task.project.project_name }}</td>
          <td>{{ task.created_at }}</td>
          <td>{{ task.updated_at }}</td>
          <td>{{ task.status.status_name }}</td>
          <td>{{ task.task_owner.username }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/core/home.html
{% extends 'core/_base.html' %} {% load socialaccount %}

{% block content %}
{% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="row content">
            <div class="col-sm-3 sidenav hidden-xs">
                <h2>Logo</h2>
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="#section1">Dashboard</a></li>
                    <li><a href="/tasks/">Tasks</a></li>
                    <li><a href="/issues/">Issues</a></li>
                    <li><a href="/projects">Projects</a></li>
                </ul><br>
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="#section1">Recent Projects</a></li>
                    {% for project in recent_projects %}
                        <li><a href="project/{{project.project_id}}/tasks">{{ project.project_name }}</a></li>
                    {% endfor %}
                </ul><br>
            </div>
            <br>
            
            <div class="col-sm-9">
                <div class="well">
                    <h4>Actions</h4>
                    {% if user_details and user_details.first.user_role.role_name == 'Project Manager' or user_details.first.user_role.role_name == 'Scrum Master' %}
                        <a href="{% url 'create_project' %}" class="btn btn-primary">Create Project</a>
                        <a href="{% url 'add_developer' %}" class="btn btn-primary">Add Developers in Project</a>
                    {% endif %}
                    <a href="{% url 'create_task' %}" class="btn btn-primary">Create Task</a>
                    <a href="{% url 'create_issue' %}" class="btn btn-primary">Create Issue</a>
                </div>
                <div class="row">
                    {% for task_count in task_counts %}
                        <div class="col-sm-3">
                            <a href="tasks/{{ task_count.status__status_name }}/{{ task_count.status__status_id }}">
                                <div class="well clickable-well">
                                    <h4>{{ task_count.status__status_name }}</h4>
                                    <p>{{ task_count.count }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                
                <div class="row">
                    <div class="col-sm-6">
                        <div class="well">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Task Name</th>
                                        <th>Project Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for task in tasks %}
                                        <tr>
                                            <td><strong>{{ task.task_name }}</strong></td>
                                            <td>{{ task.project__project_name }}</td>
                                            <td>
                                                <a href="{% url 'view_task' task.task_id %}" class="btn btn-primary">View Task</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    <div class="col-sm-6">
                        <div class="well">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Issue Name</th>
                                        <th>Project Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for issue in issues %}
                                        <tr>
                                            <td><strong>{{ issue.issue_name }}</strong></td>
                                            <td>{{ issue.project__project_name }}</td>
                                            <td>
                                                <a href="{% url 'view_issue' issue.issue_id %}" class="btn btn-primary">View Issue</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <div class="well">
                            <p>Text</p> 
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="well">
                            <p>Text</p> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
<!-- GitHub button starts here -->
<a href="{% provider_login_url 'github' %}" class="btn btn-secondary">
    <i class="fa fa-github fa-fw"></i>
    <span>Login with GitHub</span>
</a>
<!-- GitHub button ends here -->
  {% endif %}
{% endblock %}

templates/core/login.html
{% extends 'core/_base.html' %} {% load socialaccount %}

{% block content %}

<div class="container" style="text-align: center; padding-top: 10%;">
  <h1>Django Social Login</h1>

  <br /><br />

  {% if user.is_authenticated %}
    <h3>Welcome {{ user.username }} !!!</h3>
    <br /><br />
    <a href="{% url 'account_logout' %}" class="btn btn-danger">Logout</a>
    {% else %}
    <!-- GitHub button starts here -->
    <a href="{% provider_login_url 'github' %}" class="btn btn-secondary">
        <i class="fa fa-github fa-fw"></i>
        <span>Login with GitHub</span>
    </a>
    <!-- GitHub button ends here -->
    {% endif %}
</div>

{% endblock content %}

templates/core/task_detail.html
<!-- task_detail.html -->
{% extends 'core/_base.html' %}

{% block content %}
  <h2>{{ task.task_name }}</h2>
  <p>{{ task.task_description }}</p>
  <p>Assigned to: {{ task.assigned_to }}</p>
  <p>Status: {{ task.status }}</p>

  <h3>Edit Task</h3>
  <form method="post" action="/view_task/{{task.task_id}}/">
    {% csrf_token %}
    <label for="id_task_name">Task Name:</label>
    <input type="text" id="id_task_name" name="task_name" value="{{ task.task_name }}" required>

    <label for="id_task_description">Task Description:</label>
    <textarea id="id_task_description" name="task_description" required>{{ task.task_description }}</textarea>

    <label for="id_assigned_to">Assigned to:</label>
    <select id="id_assigned_to" name="assigned_to" required>
      {% for user in users %}
        <option value="{{ user.id }}" {% if user.id == task.assigned_to.id %}selected{% endif %}>{{ user.username }}</option>
      {% endfor %}
    </select>

    <label for="id_status">Status:</label>
    <select id="id_status" name="status" required>
      {% for task_status in task_statuses %}
        <option value="{{ task_status.status_id }}" {% if task_status.status_id == task.status.status_id %}selected{% endif %}>{{ task_status.status_name }}</option>
      {% endfor %}
    </select>

    <button type="submit" class="btn btn-primary">Save changes</button>
  </form>
{% endblock %}

templates/core/userproject.html
{% extends 'core/_base.html' %}

{% block content %}
    <div class="container">
        <h2>Add Developer to Project</h2>
        <form method="post" action="{% url 'add_developer' %}" class="needs-validation" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Developer</button>
        </form>
    </div>
{% endblock %}